-- ============================================================
-- 数据库初始化脚本（不破坏性模式）
-- 
-- 设计原则：
-- 1. 只创建不存在的表，不删除已有表
-- 2. 只添加不存在的列，不删除已有列
-- 3. 平时开发不会破坏已有数据
--
-- 如需完全重置数据库，请手动删除 data/ 目录下的文件
-- ============================================================

-- USERS 表：存储所有用户信息
CREATE TABLE IF NOT EXISTS USERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(64) NOT NULL UNIQUE,
    PHONE VARCHAR(20) UNIQUE,
    VERIFICATION_CODE VARCHAR(6),
    VERIFICATION_CODE_SENT_AT TIMESTAMP,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 添加 USERS 表缺失的列（如果不存在）- 在表创建之后执行
ALTER TABLE USERS ADD COLUMN IF NOT EXISTS IS_DEV_MODE BOOLEAN DEFAULT FALSE;

-- ORGANIZATIONS 表：存储组织空间信息
CREATE TABLE IF NOT EXISTS ORGANIZATIONS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(128) NOT NULL,
    DESCRIPTION VARCHAR(500),
    COLOR VARCHAR(7) DEFAULT '#409EFF',
    OWNER_ID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (OWNER_ID) REFERENCES USERS(ID)
);

-- ORGANIZATION_MEMBERS 表：存储组织成员关系
CREATE TABLE IF NOT EXISTS ORGANIZATION_MEMBERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORGANIZATION_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    ROLE VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    CAN_READ BOOLEAN NOT NULL DEFAULT TRUE,
    CAN_WRITE BOOLEAN NOT NULL DEFAULT FALSE,
    JOINED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATIONS(ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    UNIQUE (ORGANIZATION_ID, USER_ID)
);

-- INVITATIONS 表：存储企业邀请函
CREATE TABLE IF NOT EXISTS INVITATIONS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORGANIZATION_ID BIGINT NOT NULL,
    INVITED_BY_USER_ID BIGINT NOT NULL,
    INVITATION_CODE VARCHAR(32) NOT NULL,
    INVITED_PHONE VARCHAR(20),
    USED BOOLEAN NOT NULL DEFAULT FALSE,
    USED_BY_USER_ID BIGINT,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EXPIRED_AT TIMESTAMP,
    EFFECTIVE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATIONS(ID) ON DELETE CASCADE,
    FOREIGN KEY (INVITED_BY_USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (USED_BY_USER_ID) REFERENCES USERS(ID),
    UNIQUE (ORGANIZATION_ID, INVITATION_CODE)
);

-- PROJECTS 表：存储项目信息
CREATE TABLE IF NOT EXISTS PROJECTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(128) NOT NULL,
    DESCRIPTION VARCHAR(500),
    COLOR VARCHAR(7) DEFAULT '#409EFF',
    ORGANIZATION_ID BIGINT NOT NULL,
    OWNER_ID BIGINT NOT NULL,
    TYPE VARCHAR(20) DEFAULT 'API', -- UI or API
    ITEMS_JSON TEXT, -- 存储合集中的项及顺序
    CRON_EXPRESSION VARCHAR(64), -- 定时任务
    LOOP_COUNT INTEGER DEFAULT 1, -- 循环次数
    ENABLED BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATIONS(ID) ON DELETE CASCADE,
    FOREIGN KEY (OWNER_ID) REFERENCES USERS(ID)
);

-- 添加 PROJECTS 表缺失的列
ALTER TABLE PROJECTS ADD COLUMN IF NOT EXISTS TYPE VARCHAR(20) DEFAULT 'API';
ALTER TABLE PROJECTS ADD COLUMN IF NOT EXISTS ITEMS_JSON TEXT;
ALTER TABLE PROJECTS ADD COLUMN IF NOT EXISTS CRON_EXPRESSION VARCHAR(64);
ALTER TABLE PROJECTS ADD COLUMN IF NOT EXISTS LOOP_COUNT INTEGER DEFAULT 1;
ALTER TABLE PROJECTS ADD COLUMN IF NOT EXISTS UI_INSTANCE_ID BIGINT;
ALTER TABLE PROJECTS ADD COLUMN IF NOT EXISTS ENABLED BOOLEAN DEFAULT TRUE;

-- ============================================================
-- UI 测试相关表
-- ============================================================

-- UI_TEST_CASE 表：存储 UI 测试用例
CREATE TABLE IF NOT EXISTS UI_TEST_CASE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(128) NOT NULL,
    DESCRIPTION TEXT,
    MODULE_KEY VARCHAR(64) NOT NULL DEFAULT 'test',
    STEPS_JSON TEXT,
    ORGANIZATION_ID BIGINT,
    PROJECT_ID BIGINT,
    USER_ID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATIONS(ID) ON DELETE SET NULL,
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID) ON DELETE SET NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

ALTER TABLE UI_TEST_CASE ADD COLUMN IF NOT EXISTS MODULE_KEY VARCHAR(64) NOT NULL DEFAULT 'test';

-- UI_EXECUTION_INSTANCE 表：存储执行实例配置
CREATE TABLE IF NOT EXISTS UI_EXECUTION_INSTANCE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(64) NOT NULL,
    TYPE VARCHAR(32) NOT NULL,
    REMOTE_URL VARCHAR(255),
    CONFIG_JSON TEXT,
    ENABLED BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- UI_TEST_EXECUTION 表：存储 UI 测试执行记录
CREATE TABLE IF NOT EXISTS UI_TEST_EXECUTION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TEST_CASE_ID BIGINT NOT NULL,
    INSTANCE_ID BIGINT NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    OPTIONS_JSON TEXT,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    ERROR_MESSAGE TEXT,
    STOP_REQUESTED BOOLEAN NOT NULL DEFAULT FALSE,
    PROJECT_ID BIGINT,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (TEST_CASE_ID) REFERENCES UI_TEST_CASE(ID) ON DELETE CASCADE,
    FOREIGN KEY (INSTANCE_ID) REFERENCES UI_EXECUTION_INSTANCE(ID)
);

ALTER TABLE UI_TEST_EXECUTION ADD COLUMN IF NOT EXISTS PROJECT_ID BIGINT;

-- UI_EXECUTION_STEP 表：存储 UI 测试执行步骤详情
CREATE TABLE IF NOT EXISTS UI_EXECUTION_STEP (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EXECUTION_ID BIGINT NOT NULL,
    STEP_INDEX INTEGER NOT NULL,
    STEP_TYPE VARCHAR(32),
    ACTION VARCHAR(64),
    STATUS VARCHAR(32) NOT NULL,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    ERROR_MESSAGE TEXT,
    SCREENSHOT_PATH VARCHAR(512),
    LOG_TEXT TEXT,
    RAW_STEP_JSON TEXT,
    FOREIGN KEY (EXECUTION_ID) REFERENCES UI_TEST_EXECUTION(ID) ON DELETE CASCADE
);

-- ============================================================
-- API 测试相关表
-- ============================================================

-- API_COLLECTION 表：存储 API 测试集合（树形结构）
CREATE TABLE IF NOT EXISTS API_COLLECTION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(128) NOT NULL,
    DESCRIPTION VARCHAR(500),
    NODE_TYPE VARCHAR(20) NOT NULL DEFAULT 'FOLDER',
    PARENT_ID BIGINT,
    STOP_ON_FAIL BOOLEAN NOT NULL DEFAULT FALSE,
    METHOD VARCHAR(10),
    URL VARCHAR(2000),
    PARAMS_JSON TEXT,
    HEADERS_JSON TEXT,
    BODY_TYPE VARCHAR(20),
    BODY_RAW TEXT,
    BODY_RAW_TYPE VARCHAR(20),
    BODY_FORM TEXT,
    AUTH_TYPE VARCHAR(20),
    AUTH_CONFIG TEXT,
    ASSERTIONS TEXT,
    USER_ID BIGINT NOT NULL,
    ORGANIZATION_ID BIGINT,
    PROJECT_ID BIGINT,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PARENT_ID) REFERENCES API_COLLECTION(ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATIONS(ID) ON DELETE SET NULL,
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID) ON DELETE CASCADE
);

-- API_TEST_EXECUTION 表：存储 API 测试执行记录
CREATE TABLE IF NOT EXISTS API_TEST_EXECUTION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    COLLECTION_ID VARCHAR(100),
    COLLECTION_NAME VARCHAR(255),
    STATUS VARCHAR(20) NOT NULL DEFAULT 'SUCCESS',
    REQUEST_JSON TEXT,
    RESPONSE_JSON TEXT,
    DURATION INTEGER,
    HTTP_STATUS INTEGER,
    STATUS_TEXT VARCHAR(255),
    ASSERTIONS_JSON TEXT,
    ERROR_MESSAGE TEXT,
    REQUEST_HEADERS TEXT,
    REQUEST_BODY TEXT,
    RESPONSE_HEADERS TEXT,
    RESPONSE_BODY TEXT,
    USER_ID BIGINT NOT NULL,
    PROJECT_ID BIGINT,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

ALTER TABLE API_TEST_EXECUTION ADD COLUMN IF NOT EXISTS PROJECT_ID BIGINT;

-- API_ENVIRONMENT 表：存储 API 环境配置
CREATE TABLE IF NOT EXISTS API_ENVIRONMENT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(128) NOT NULL,
    VARIABLES_JSON TEXT,
    GLOBAL_VARIABLES_JSON TEXT,
    USER_ID BIGINT NOT NULL,
    PROJECT_ID BIGINT,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID) ON DELETE CASCADE
);

ALTER TABLE API_ENVIRONMENT ADD COLUMN IF NOT EXISTS VARIABLES_JSON TEXT;
ALTER TABLE API_ENVIRONMENT ADD COLUMN IF NOT EXISTS GLOBAL_VARIABLES_JSON TEXT;
ALTER TABLE API_ENVIRONMENT ADD COLUMN IF NOT EXISTS USER_ID BIGINT;

-- SCRIPT_LIBRARY 表：存储脚本库（Python 函数）
CREATE TABLE IF NOT EXISTS SCRIPT_LIBRARY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FUNCTION_NAME VARCHAR(64) NOT NULL UNIQUE,
    SCRIPT_NAME VARCHAR(128),
    DESCRIPTION TEXT,
    CONTENT TEXT NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    PROJECT_ID BIGINT,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID) ON DELETE CASCADE
);

-- ============================================================
-- 系统设置相关表
-- ============================================================

-- USER_SETTINGS 表：存储用户个人设置
CREATE TABLE IF NOT EXISTS USER_SETTINGS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL UNIQUE,
    THEME_MODE VARCHAR(20) NOT NULL DEFAULT 'light',
    NOTIFY_ON_COMPLETE BOOLEAN NOT NULL DEFAULT TRUE,
    LANGUAGE VARCHAR(10) DEFAULT 'zh-CN',
    PAGE_SIZE INT DEFAULT 20,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

-- ORG_CONFIG 表：存储组织级别的配置信息
CREATE TABLE IF NOT EXISTS ORG_CONFIG (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORGANIZATION_ID BIGINT NOT NULL UNIQUE,
    DEFAULT_BROWSER VARCHAR(20) NOT NULL DEFAULT 'chrome',
    DRIVER_MODE VARCHAR(20) NOT NULL DEFAULT 'local',
    REMOTE_URL VARCHAR(255),
    STEP_TIMEOUT INT NOT NULL DEFAULT 30,
    SCREENSHOT_STRATEGY VARCHAR(20) NOT NULL DEFAULT 'on_failure',
    WINDOW_SIZE VARCHAR(20) NOT NULL DEFAULT '1920x1080',
    API_TIMEOUT INT NOT NULL DEFAULT 30000,
    PROXY_SERVER VARCHAR(255),
    SSL_VERIFY BOOLEAN NOT NULL DEFAULT TRUE,
    RETRY_COUNT INT NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATIONS(ID)
);
